### ISSUE TITLE
ConfigCrypter Might be Inhibiting Loading of {Env}-specific appsettings.json Files

### ISSUE THREAD

**Issue by Becca37** [devattic/ConfigCrypter#2]
I have encountered a seeming issue where using DevAttic's ConfigCrypter nullifies the loading of {env}-based appsettings files.

History

This was encountered first in a production application where I had NOT been using {env}-based appsettings files when I added ConfigCrypter to that project. I later decided to make use of the feature to make my life easier vs. the code gyrations needed to check environments and pull a different value in the sole appsettings file based on that value. I found it was not using the appsettings {env}-specific files and assumed (still do) it was something I'd misconfigured so created a fresh project for testing.

For more info, check out the steps to reproduce on the [sample project](https://github.com/Becca37/TestingMultiEnvWithConfigCrypter) I tossed together. Maybe someone can see where I went wrong!

**Comment by devattic-developer** [comment]
Hey!
Sorry for the late answer. I will try to have a look at it in the next days.

**Comment by Becca37** [comment]
Just checking back in on this now as I've started another project where I'd really love to make use of appsettings.{Environment}.json files for the ASP.NET Core web application, along with being able to encrypt the sensitive data within the files. Think it's possible / am I missing a setting somewhere that's preventing it from working as I hope?

**Comment by mrukas** [comment]
Hi!
Sorry that it took this long. I released a new version of the library (1.1.0) that is capable of decrypting environment specific appsettings files.

**Comment by Becca37** [comment]
Thanks so much!
